env: "local"
redis_conn: "localhost:6379"
postgres_conn: "postgres://postgres:postgres@localhost:5432/ttps?sslmode=disable"
http_server:
  address: "localhost:8096"
  req_timeout: 4s
  idle_timeout: 60s